### ISSUE TITLE
Ikke et problem, men heller et spørsmål: Hvorfor synkes ikke dagens transaksjoner?

### ISSUE THREAD

**Issue by yonyonson** [stenjo/SbankenToYNAB#1]
Hei,

jeg ser at du har definert at det er kun gårdsdagens og tidligere transaksjoner som skal hentes fra SBanken sitt API for synking med YNAB (ref: https://github.com/stenjo/SbankenToYNAB/blob/master/sync_accounts.py#L34 ).
Jeg lurer på hvorfor er det sånn? Det ender opp med at ingen transaksjoner som er registrerte i dag er synlige i YNAB, og siden det er en del transaksjoner som allerede kommer inn med 1-2 dagers venting blir det fort 2-3 dager venting før den faktiske betalingen havner i YNAB.

Mvh,
Petr

PS: Jeg skjønner at det er kun transkaksjoner som er faktisk gjennomført som teller, så reservering av penger på konto regnes ikke med som betaling.

**Comment by steoj** [comment]
Hei Petr,
Så vidt jeg husker fikk jeg feilmelding når jeg forsøkte å hente transaksjoner fram til og med dagens dato. Må innrømme at jeg ikke har brukt mye tid på å finne veier rundt det, så det kan godt hende det er en enkel løsning på å inkludere dagens transaksjoner i listen.
Jeg er helt enig i at det kan ta flere dager før transaksjonen blir registrert i ynab - spesielt irriterende er det transaksjoner på fredag ettermiddag ikke er i ynab før tirsdag...

**Comment by yonyonson** [comment]
Yepp :) Jeg har foreløpig rettet den med å kommentere vekk ` - datetime.timedelta(1)`, det virker foreløpig!

**Comment by steoj** [comment]
Flott. Kanon om du kan lage en pull request også så blir det riktig :-)

**Comment by stenjo** [comment]
Hm, ser ut til at dagens transaksjoner - i noen tilfeller i alle fall - endres neste dag. Noen ganger, når belastningen medfører valutakonvertering, endres også beløpet. Når YNAB oppdateres da, blir ikke endringen med men en ny transaksjon opprettes...

**Comment by yonyonson** [comment]
Ja, det gjelder transaksjoner som er eldre enn 1 dag også. Det går på at pengene reseveres først, men faktisk trekkes senere, og valutakurset kan forandre seg i mellomtiden.
Da matcher ikke YNAB transaksjonens synk id lenger (beløpet er annerledes), og en ny transaksjon er blitt opprettet. Det er to valg her:
* Enten føre transaksjoner med en gang. Da er det risiko at beløpet kan forandre seg når transkasjonen ferdigstilles. Da får man mer oppdatert men mindre presis budsjett.
* Eller føre transaksjoner når de "ferdigstilles". Da kommer transaksjoner tregere, men det blir forhåpentligvis mer presis.
Jeg foretrekker heller å føre transaksjoner med en gang, og heller fjerne / korrigere endringer, evt brukes reconciliation i YNAB, men jeg forstår at dette er smaksspørsmål.

**Comment by stenjo** [comment]
Begge er egentlig litt ufulstendige.
Ser jo (og kan verifisere) at vi kan oppdatere YNAB transaksjoner via https://api.youneedabudget.com/v1#/Transactions/updateTransactions
men må finne tilbake til en referanse på ett eller annen måte.
I vanlige transaksjoner fra SBanken har vi inngen referanse vi kan knytte ting opp mot, men dersom transaksjonen også inneholder en 'cardDetails' inneholder den igjen en 'transactionId'. Kan vi i første omgang legge inn denne transactionId inn i Memo-feltet i ynab så kan vi kanskje finne igjen transaksjonen og heller oppdatere den i stede for å lage nye? Da unngår vi også at vi klusser med ynabs 'import_id'

**Comment by stenjo** [comment]
Vi kan vel også sjekke på 'isReservation': True, for evt å ikke ta med reserverte transaksjoner via en setting et eller annet sted?
Kanskje den enkleste endringen det da.

Forslag: Hva med å sette opp i api_settings.py en linje som definerer 
```
# Set if transaction sync also should include reserved transactions.
# Transactions may change when confirmed and updates to YNAB may have to be done manually
includeReservedTransactions = True

```

**Comment by yonyonson** [comment]
Det med å ha en ekstra instilling for å ta med eller ikke ta med reservasjoner er en veldig god idee, synes jeg.

Den burde være `False` i utgangspunktet, slik at det blir minst mulig forvirring, men transaksjonene kommer ikke noe senere.

**Comment by yonyonson** [comment]
Angående hvordan er det beste å håndtere kjøp i andre valutaer enn NOK, hvor beløpet kan plutselig oppdatere seg: Jeg prøver å tråle YNAB sitt forum her: https://support.youneedabudget.com/category/accounts-transactions

Denne problemstillingen ser på ingen måte unik ut, det må være noen der som har kommer over det samme før og løste det..

**Comment by yonyonson** [comment]
Jeg stilte spørsmålet selv :) https://support.youneedabudget.com/t/x1a1vr

**Comment by stenjo** [comment]
Veldig bra. Forsket litt mer på Transaction id fra Sbanken i går og det ser ikke ut til at denne finnes før transaksjonen er verifisert, dessverre. Det betyr at vi ikke kan bruke Transaction Id for å linke oppdaterte betalinger.

**Comment by stenjo** [comment]
Har gjort noen oppdateringer som gjør at Reserverte transaksjoner blir oppdatert helt til de ikke lenger er reserverte. Har også gjort en endring som gjør at to like transaksjoner på samme dag med samme beløp faktisk legges inn begge gangene i YNAB.
Se gjerne på de endringene så lenge.

**Comment by stenjo** [comment]
Tror de siste endringene langt på vei rydder i problematikken vi har diskutert her. Om vi har en reservert transaksjon som endrer beløp når den er bekreftet vil vi ha to transaksjoner i YNAB: En som har "Reserved:" i begynnelsen av memo-feltet og en (den bekreftede) som ikke har det. Da er det en enkel manuell kontroll å slette den som står som Reservert når du har den som er bekreftet i tillegg. 
Det blir altså ikke helt automatisk men jeg finner heller ingen transaksjons-referanse i de reserverte transaksjonene fra SBanken som man kan bruke for å knytte dem sammen.
Foreslår at vi lukker denne saken nå og så får vi ta opp dette i en annen tråd når vi evt finner en løsning på spørsmålet du la inn i forumet.
