### ISSUE TITLE
Issue with transactions?

### ISSUE THREAD

**Issue by laien** [stenjo/SbankenToYNAB#13]
Hi,
It seems like I have an issue with transactions. I only get transfers and money that are coming into the account. Is it a change in the APIs or so? Do you have the same problem?

**Comment by stenjo** [comment]
Need some more information on this. What is your settings?
Did this work before and suddenly failed without any changes?

**Comment by stenjo** [comment]
Still an issue with this one?

**Comment by stenjo** [comment]
Lukker denne på grunn av mangel på mer informasjon.
