### ISSUE TITLE
Synching preliminary transactions is not working

### ISSUE THREAD

**Issue by thorep** [stenjo/SbankenToYNAB#16]
This suddenly stopped working. Have tried setting the flag to False and True...nothing...

**Comment by stenjo** [comment]
Mine too. Have to have a look at it during the weekend.

**Comment by thorep** [comment]
Okay👍 My budgets goes out of the windows without this script!:P

**Comment by thorep** [comment]
Any updates on this issue?

**Comment by stenjo** [comment]
Sems like the SBanken transaction feed stopped sending unconfirmed transactions. Have yet to investigate what have changed at the SBanken API.

**Comment by thorep** [comment]
Oh.. i hope they will add it back. Its hard keepting track if YNAB is always a couple of days behind

**Comment by yonyonson** [comment]
Hehe, oppdaget samme feilen her. @stenjo oppdaterer du ticket når du finner ut av mer?

**Comment by yonyonson** [comment]
Jeg har opprettet den der: https://github.com/Sbanken/api-examples/issues/66
Vi får se om de svarer noe :)

**Comment by thorep** [comment]
@yonyonson får transaksjoner etter 12 men kun de som er ferdig, ikke reserverte..

**Comment by yonyonson** [comment]
@thorep Skjønner. Vi får se hva SBanken sier.

**Comment by thorep** [comment]
Noen som har testet noe mer? Fungerer fortsatt ikke?

**Comment by stenjo** [comment]
Samme status. Min erfaring er at responstiden fra SBanken på ting som har med eksperimentelle api'er å gjøre er heller lang...

**Comment by adrianke** [comment]
I managed to get this working by removing the `endDate` parameter from Helpers.get_transactions_period. Without any end date, the API returns preliminary transactions as it used to.

**Comment by stenjo** [comment]
> I managed to get this working by removing the `endDate` parameter from Helpers.get_transactions_period. Without any end date, the API returns preliminary transactions as it used to.

Seems to be the case. Have removed the query param in the SBanken request. Should work now.
