### ISSUE TITLE
name 'payee_name' is not defined

### ISSUE THREAD

**Issue by rholthe** [stenjo/SbankenToYNAB#20]
Programmet klarer ikke finne "payee", og synkroniseringen stopper opp. Problemet knytter seg til en intern transaksjon mellom egne kontoer (som får tittel nettgiro). Hvordan løses dette?

**Når jeg kjører "sync_accounts.py" får jeg denne feilmeldingen**
Traceback (most recent call last):
  File "/home/ragnar/ynabsync/sync_accounts.py", line 123, in <module>
    ynab_transaction.payee_name = payee_name
NameError: name 'payee_name' is not defined

**Feilmedingen fra "GetStatementsAllAccounts.py" :** 
Traceback (most recent call last):
  File "/home/ragnar/ynabsync/Helpers.py", line 380, in getPayee
    res = (payee[2] + ' ' + payee[3]).capitalize()
IndexError: list index out of range

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./ynabsync/GetStatementsAllAccounts.py", line 44, in <module>
    main()
  File "./ynabsync/GetStatementsAllAccounts.py", line 35, in main
    payee = getPayee(item)
  File "/home/ragnar/ynabsync/Helpers.py", line 382, in getPayee
    raise ValueError ("Can't extract payee from nettgiro.")
ValueError: Can't extract payee from nettgiro.

**Comment by stenjo** [comment]
Ser på denne feilen nå. Ville vært til stor hjelp om du kunne lagt inn denne kodelinjen:
`print(transaction)`
etter linje 378 (altså som ny linje 379) i Helpers.py og sendt meg utskrift av terminal når du kjører programmene du beskriver.
Husk at linjen må ha samme innrykk som llinjen etter.

**Comment by rholthe** [comment]
Fungerer nå.  Regner med at transaksjonen var såpass ny at den ikke hadde fått noe navn enda. Nytt forsøk etter noen timer og da fungerte alt som før.
