### ISSUE TITLE
Grants required - HTTP 401

### ISSUE THREAD

**Issue by adrianke** [stenjo/SbankenToYNAB#26]
It appears that you must grant the following access to your token in Sbanken Utviklerportal: "Grants access to perform operations on APIBeta APIs (aka. developer portal)". Without this, every request return HTTP 401.

I think this changed when the base domain was changed, as it worked before I pulled the latest changes from git.

I spent quite some time to debug this, so the README should probably get updated with this detail. I already had every read access granted and thus thought that the grants were fine.

**Comment by stenjo** [comment]
Thanks for your input. README is updated and hopefully other adopters will not have the same issues as you have had.
